### ISSUE TITLE
hamburger popup takes 1-3 seconds to load menu

### ISSUE THREAD

**Issue by neuromusic** [napari/napari-sphinx-theme#23] opened 2021-10-14 23:53 UTC
*from October 2021 pre-launch bug bash*

**Created by**: Justin

## Description 

on an older iPad (safari), when I click the hamburger, it takes 1-3 seconds for the menu to pop up

## Info

**Bug source**: *unknown*

**Browser**: safari

**PR**: *none*

**Comment by codemonkey800** [comment] 2022-03-30 16:53
@neuromusic can you see if this is still an issue please?

**Comment by psobolewskiPhD** [comment] 2024-01-18 20:02
I can't reproduce this on mobile and it's pretty old, so closing. If it is still an issue please re-open or make a new one.

**Closed by psobolewskiPhD** 2024-01-18 20:02 UTC
Labels: enhancement, P3
