### ISSUE TITLE
Dropdown admonitions sporadically expand incorrectly on Windows Chrome & Edge

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari-sphinx-theme#120] opened 2022-07-17 15:42 UTC
This one is super sporadic and difficult to reproduce, unfortunately, but on Windows Chrome & Edge, sometimes when trying to open the admonitions e.g. [in the install guide](https://napari.org/tutorials/fundamentals/installation.html#install-as-python-package-recommended), only the first one will open.

So on first load, you can open the `1. From pip` admonition, but then even when clicking number 2 or 3, the `1. From pip` block is still the one that opens. A user at SciPy sprints was able to reproduce on Chrome and Edge, but I haven't been able to consistently reproduce this on Windows on another machine. @codemonkey800 I'm not sure if you have any immediate ideas based on your fix from #118 🤷‍♀️

**Comment by psobolewskiPhD** [comment] 2024-01-18 19:56
I can't reproduce, I think we can close this and if it pops up again we can address.

**Closed by psobolewskiPhD** 2024-01-18 19:56 UTC
