### ISSUE TITLE
"Hide Search Matches" box has low contrast on home page

### ISSUE THREAD

**Issue by dstansby** [napari/napari-sphinx-theme#169] opened 2024-07-16 10:15 UTC
## 📚 Documentation

At https://napari.org/stable/index.html:

<img width="1021" alt="Screenshot 2024-07-16 at 11 15 03" src="https://github.com/user-attachments/assets/a722f26b-3d5f-4f4a-a036-a9aca3003ef7">

The black box at the top says "Hide Search Matches", but it's very low contrast so not very readable.

**Comment by psobolewskiPhD** [comment] 2024-07-17 01:39
I can't reproduce (macOS Safari Light mode), but maybe this is a light mode/dark mode or browser issue?
<img width="460" alt="image" src="https://github.com/user-attachments/assets/55ba42ac-48f1-491b-acdb-c68b060d8f1e">

**Comment by dstansby** [comment] 2024-07-17 07:58
I'm on Firefox 128 on macOS if that helps?

**Comment by melissawm** [comment] 2024-07-29 12:41
Closed by #171

**Closed by melissawm** 2024-07-29 12:41 UTC
Labels: bug
